name: linter
on: push
jobs:
  linter-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make-lint
        run: |
          pip install poetry
          make lint